### ISSUE TITLE
Is this working? 

### ISSUE THREAD

**Issue by AngelinCalu** [MitrophD/vue-intl-tel-input#1]
Is this working? Any example on how to implement it ?

**Comment by MitrophD** [comment]
Hi! U can download example from this link https://dl.dropboxusercontent.com/u/25298147/Vue.zip

**Comment by AngelinCalu** [comment]
I believe the `flags.png` files is missing from the example (and package). 
There is one `flags@2x.png` but renaming it to `flags.png` will show strange images instead of flags.

**Comment by loama** [comment]
Hi! could you provide the flags.png image?
