### ISSUE TITLE
Provide examples

### ISSUE THREAD

**Issue by timur-orudzhov** [MitrophD/vue-intl-tel-input#2]
Hi, @MitrophD ! It would be useful, if you provide some usage examples. Thanks for the plugin.

**Comment by MitrophD** [comment]
Hi Timer.Yes of course. U can download example from this link https://www.dropbox.com/s/vfy8lqcn4dorp17/Vue.zip?dl=0

**Comment by MitrophD** [comment]
Hi Timur! I gave you a link to an example. Did it help you?
