### ISSUE TITLE
when I use vue2.0, I can't use it

### ISSUE THREAD

**Issue by qq20004604** [MitrophD/vue-intl-tel-input#3]
I find some errors when use it.
Log1:
`Handy.js:778 Error: Module build failed: SyntaxError: ............/vue-intl-tel-input.vue: Unexpected token (438:38)

[0m [90m 436 | [39m                [36mdebugger[39m
 [90m 437 | [39m                console[33m.[39mlog(countryCopie[33m,[39m countries)[33m;[39m
[31m[1m>[22m[39m[90m 438 | [39m                [36mconst[39m countryCopie [33m=[39m {[33m...[39mcountries}[33m;[39m
 [90m     | [39m                                      [31m[1m^[22m[39m
 [90m 439 | [39m
 [90m 440 | [39m                [36mthis[39m[33m.[39mtoFront[33m.[39mforEach((code) [33m=>[39m {
 [90m 441 | [39m                    [36mdelete[39m countryCopie[code][33m;[39m[0m
`

Log2:
`VM11536:1 Uncaught (in promise) Error: Module build failed: SyntaxError: .........../vue-intl-tel-input.vue: Unexpected token (438:38)

[0m [90m 436 | [39m                [36mdebugger[39m
 [90m 437 | [39m                console[33m.[39mlog(countryCopie[33m,[39m countries)[33m;[39m
[31m[1m>[22m[39m[90m 438 | [39m                [36mconst[39m countryCopie [33m=[39m {[33m...[39mcountries}[33m;[39m
 [90m     | [39m                                      [31m[1m^[22m[39m
 [90m 439 | [39m
 [90m 440 | [39m                [36mthis[39m[33m.[39mtoFront[33m.[39mforEach((code) [33m=>[39m {
 [90m 441 | [39m                    [36mdelete[39m countryCopie[code][33m;[39m[0m`

Log3:
`./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/vue-intl-tel-input.vue
Module build failed: SyntaxError: .........../vue-intl-tel-input.vue: Unexpected token (438:38)

> 436 |                 const countryCopie = {...countries};
      |                                       ^
  437 | 
  438 |                 this.toFront.forEach((code) => {
  439 |                     delete countryCopie[code];`

**Comment by MitrophD** [comment]
Hi!You can use it https://www.dropbox.com/s/vfy8lqcn4dorp17/Vue.zip?dl=0
